---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      nodeSelector:
        role: server
      containers:
      - name: game-2048
        image: alexwhen/docker-2048:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
spec:
  selector:
    app: game-2048
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Specify a node port
  type: NodePort